config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :sessions, only:[:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :attendances, only:[:index, :create, :edit, :update]
  resources :quizzes do
    collection do
      get 'search'
    end
  end
  #get '*path', controller: 'application', action: 'render_404'
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: %i[ show edit update destroy ]
  before_action :set_q, only: [:index, :search]

  # GET /quizzes or /quizzes.json
  def index
    @quizzes = @q.result
    @quizzes = Quiz.order(:created_at).page(params[:page]) 
  end

  # GET /quizzes/1 or /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes or /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to quiz_url(@quiz), notice: "登録しました。" }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1 or /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to quiz_url(@quiz), notice: "更新しました。" }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1 or /quizzes/1.json
  def destroy
    @quiz.destroy

    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: "削除しました。" }
      format.json { head :no_content }
    end
  end
  
  def search
    @results = @q.result
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end
    
    def set_q
      @q = Quiz.ransack(params[:q])
    end

    # Only allow a list of trusted parameters through.
    def quiz_params
      params.require(:quiz).permit(:question, :answer, :image, :destination)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz, local: true) do |form| %>
    <% if quiz.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

        <ul>
          <% quiz.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field mb-3">
      <%= form.label :問題 %>
      <%= form.text_area :question, class: "form-control", rows:"2" %>
  </div>

  <div class="field mb-3">
      <%= form.label :解答 %>
      <%= form.text_area :answer, class: "form-control", rows:"4" %>
  </div>

  <div class="field mb-3">
      <%= form.label :写真 %>
      <%= form.file_field :image %>
  </div>

  <div class="field mb-3">
      <%= form.label :方面 %>
      <%= form.select :destination, [:Asia, :Europe, :Oceania, :Americas, :Africa], { class: 'form-control' , required: true } %>
  </div>

  <div class="actions mb-3">
      <%= form.submit value="登録", class: 'btn btn-outline-primary btn-lg' %>
  </div>
<% end %>

app/views/quizzes/_search_form.html.erb
<%= search_form_for @q, url: search_quizzes_path do |f|%>
    <div class="form-check form-check-inline">
      <%= f.radio_button :destination_eq, '' %>指定なし
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :destination_eq, 0 %>Asia
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :destination_eq, 1 %>Europe
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :destination_eq, 2 %>Oceania
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :destination_eq, 3 %>Americas
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :destination_eq, 4 %>Africa
    </div>
    <%= f.submit '方面別検索', class: "btn btn-outline-primary btn-lg" %>
<% end %>

app/views/quizzes/edit.html.erb
<% if current_user.is_admin? %>
  <div class="w-100 d-flex flex-column align-items-center">
    <h4>クイズを編集</h4>
    <%= link_to 'クイズ一覧に戻る', quizzes_path, class: 'btn btn-outline-primary btn-lg mb-3' %>
    <%= render 'form', quiz: @quiz %>
  </div>
<% end %>

app/views/quizzes/index.html.erb
<% if current_user.is_admin? %>
  <div class="w-100 d-flex flex-column align-items-center">
    <h4>クイズ一覧</h4>
    <h4><%= link_to 'クイズ新規登録', new_quiz_path, class: 'btn btn-outline-primary btn-lg' %></h4>
    <%= render 'search_form' %>
    <h4><%= paginate @quizzes %></h4>
  </div>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">方面</th>
        <th scope="col">問題</th>
        <th scope="col">写真</th>
        <th scope="col">画像ファイル</th>
        <th scope="col">解答</th>
        <th scope="col">詳細</th>
        <th scope="col">編集</th>
        <th scope="col">削除</th>
      </tr>
    </thead>

    <tbody>
      <% @quizzes.each do |quiz| %>
        <tr>
          <td><%= quiz.destination %></td>
          <td><%= quiz.question %></td>
          <td><%= image_tag quiz.image.variant(resize_to_limit: [200, 200]) if quiz.image.attached? %></td>
          <td><%= link_to quiz.image.filename, quiz.image if quiz.image.attached? %></td>
          <td><%= quiz.answer %></td>
          <td><%= link_to '表示', quiz, class: 'btn btn-outline-primary' %></td>
          <td><%= link_to '編集', edit_quiz_path(quiz), class: 'btn btn-outline-primary' %></td>
          <td><%= link_to '削除', quiz, method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-outline-danger'%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/quizzes/new.html.erb
<% if current_user.is_admin? %>
  <div class="w-100 d-flex flex-column align-items-center">
    <h4>クイズ新規登録</h4>
    <%= link_to 'クイズ一覧に戻る', quizzes_path ,class: 'btn btn-outline-primary btn-lg' %>
    <%= render 'form', quiz: @quiz %>  
  </div>
<% end %>

app/views/quizzes/search.html.erb
<div class="w-100 d-flex flex-column align-items-center">
  <h4>検索結果</h4>
  <%= link_to 'クイズ一覧に戻る', quizzes_path, class: 'btn btn-outline-primary btn-lg mb-3' %>
</div>

<table class="table">
    <thead>
      <tr>
        <th scope="col">方面</th>
        <th scope="col">問題</th>
        <th scope="col">写真</th>
        <th scope="col">画像ファイル</th>
        <th scope="col">解答</th>
        <th scope="col">詳細</th>
        <th scope="col">編集</th>
        <th scope="col">削除</th>
      </tr>
    </thead>

    <tbody>
      <% @results.each do |quiz| %>
        <tr>
        <td><%= quiz.destination %></td>
        <td><%= quiz.question %></td>
        <td><%= image_tag quiz.image.variant(resize_to_limit: [200, 200]) if quiz.image.attached? %></td>
        <td><%= link_to quiz.image.filename, quiz.image if quiz.image.attached? %></td>
        <td><%= quiz.answer.truncate(50) %></td>
        <td><%= link_to '表示', quiz , class: 'btn btn-outline-primary' %></td>
        <td><%= link_to '編集', edit_quiz_path(quiz), class: 'btn btn-outline-primary' %></td>
        <td><%= link_to '削除', quiz, method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-outline-danger'%></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/quizzes/show.html.erb
<div class="w-100 d-flex flex-column align-items-center">
  <h4>
    <strong>方面:</strong>
    <%= @quiz.destination %>
  </h4>
  
  <h4>
    <strong>Q:</strong>
    <%= @quiz.question %>
  </h4>

  <h4 id="timer"><span id="count" class="text-primary">5</span>秒後に答え合わせ</h4>
 
  <div>
    <%#= link_to @quiz.image.filename, @quiz.image if @quiz.image.attached? %>
    <%= image_tag @quiz.image.variant(resize_to_limit: [400, 400]) if @quiz.image.attached? %>
  </div>
  
  <div id="answer" style="display: none;">
    <p class="m-3 btn btn-success btn-lg eachTextAnime"><%= @quiz.answer %></p>
  </div>
  
  <script>
    var count = document.getElementById("count");
    setInterval(function(){count.innerHTML--;},1000);
    setTimeout(function(){document.getElementById("answer").style.display="block";},5000);
    setTimeout(function(){document.getElementById("timer").style.display="none";},5000);
  </script>   

  <% if current_user == @user || current_user.is_admin? %>
    <%= link_to 'クイズ一覧に戻る', quizzes_path, class: 'btn btn-outline-primary btn-lg m-4' %>
  <% end %>
</div>