config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :sessions, only:[:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :attendances, only:[:index, :create, :edit, :update]
  resources :quizzes do
    collection do
      get 'search'
    end
  end
  #get '*path', controller: 'application', action: 'render_404'
end

app/models/user.rb
class User < ApplicationRecord
  validates :company, presence: true, length: { maximum: 3 }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :attendances, dependent: :destroy

  def today_attendance
    Attendance.where(created_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day, user_id: id).first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:show, :edit, :update]
  skip_before_action :login_required, only: [:new, :create]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end 

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "ユーザ情報を更新しました！" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:company, :name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to current_user unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="w-100 d-flex flex-column align-items-center">
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this quiz from being saved:</h2>
  
        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
 
    <div class="field mb-3">
      <%= form.label :名前 %>
      <%= form.text_area :name, class: "form-control" %>
    </div>
  
    <div class="field mb-3">
      <%= form.label :メールアドレス %>
      <%= form.email_field :email, class: "form-control" %>
    </div>
  
    <div class="field mb-3">
      <%= form.label :パスワード %>
      <%= form.password_field :password, class: "form-control" %>
    </div>
    
    <div class="field mb-3">
      <%= form.label :パスワード再入力 %>
      <%= form.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <div class="actions mb-3">
      <%= form.submit value="更新", class: 'btn btn-outline-primary btn-lg' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="w-100 d-flex flex-column align-items-center">
  <h4>ユーザー情報を編集</h4>
  <%= render 'form', user: @user %>
</div>

app/views/users/new.html.erb
<div class="w-100 d-flex flex-column align-items-center">
  <h4>新規登録</h4>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @user, local: true) do |f| %>
      <%= f.label :企業コード %>
      <%= f.text_field :company, class: "form-control" %>

      <%= f.label :名前 %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :メールアドレス %>
      <%= f.email_field :email, class: "form-control"  %>
    
      <%= f.label :パスワード %>
      <%= f.password_field :password, class: "form-control", id: "pass"  %>
      
      <%= f.label :パスワード再入力 %>
      <%= f.password_field :password_confirmation, class: "form-control", id:"pass" %>
      
      <%= f.submit "登録", class: 'btn btn-outline-primary btn-lg m-3' %>  
  <% end %>
</div>

app/views/users/show.html.erb
<div class="w-100 d-flex flex-column align-items-center"> 
  <h4>企業 <%= @user.company %></h4>
  <h4><%= @user.name %></h4>
  <h4><%= @user.email %></h4>
  <%= render 'shared/date' %>
</div>

<%= button_to '打刻する', {:controller => "attendances", :action => "create"}, class: "btn btn-primary w-100 my-3", style:"height: 150px" %>

<nav class="navbar navbar-expand-lg btn-group w-100 mb-3" role="group" aria-label="Basic outlined example">
  <%= link_to '勤怠状況一覧', attendances_path, class: 'btn btn-outline-primary btn-lg' %>
  <% if current_user.is_admin? %>
    <%= link_to 'クイズ一覧', quizzes_path, class: 'btn btn-outline-primary btn-lg' %>
  <% end %>
  <%= link_to 'ユーザー情報編集', edit_user_path, class: 'btn btn-outline-primary btn-lg' %>
</nav>