config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :sessions, only:[:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :attendances, only:[:index, :create, :edit, :update]
  resources :quizzes do
    collection do
      get 'search'
    end
  end
  #get '*path', controller: 'application', action: 'render_404'
end

app/views/shared/_date.html.erb
<% date = Date.today
weeks = ["月","火","水","木","金","土","日"] 
index = date.strftime("%u").to_i 
%>


<h4><%= date.strftime("%Y年%-m月%-d日 #{weeks[index - 1]}曜日") %></h4>
<h4 id="RealtimeClock"></h4>

<script>
function set2fig (num){
    var fig;
      if(num < 10) {fig = "0" + num;}
      else {fig = num;}
      return fig;
}
function showClock() {
  var nowTime = new Date(); 
  var nowHour = set2fig(nowTime.getHours());
  var nowMin  = set2fig(nowTime.getMinutes());
  var nowSec  = set2fig(nowTime.getSeconds());
  var msg = nowHour + ":" + nowMin + ":" + nowSec;
  document.getElementById("RealtimeClock").innerHTML = msg;
}
setInterval('showClock()',1000);
</script>

app/views/shared/_footer.html.erb
<footer>
  <div class="fixed-bottom" style="height:30px; text-align: center">© Goto Kintai</div>
</footer>

app/views/shared/_header.html.erb
<% if logged_in? %>
      <nav class="navbar navbar-expand-lg btn-group w-100" role="group" aria-label="Basic outlined example">
        <%= link_to "マイページ", user_path(current_user.id), class: 'btn btn-outline-primary btn-lg' %>
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete, class: 'btn btn-outline-primary btn-lg' %>
      </nav>    
<% else %>
      <nav class="navbar navbar-expand-lg btn-group w-100" role="group" aria-label="Basic outlined example">
        <%= link_to "新規登録", new_user_path, class: 'btn btn-outline-primary btn-lg' %>
        <%= link_to "ログイン", new_session_path, class: 'btn btn-outline-primary btn-lg' %>
      </nav>
<% end %>