config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :sessions, only:[:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :attendances, only:[:index, :create, :edit, :update]
  resources :quizzes do
    collection do
      get 'search'
    end
  end
  #get '*path', controller: 'application', action: 'render_404'
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  validate :date_chk, on: :create
  validate :start_end_check, on: :update

  def time_diff
    (end_at - start_at) / 3600
  end

  def start_end_check
    errors.add(:end_at) if self.start_at >= self.end_at
  end
  
  private
  def date_chk
    errors.add(:user_id) if Attendance.where("user_id = ? AND DATE(created_at) = DATE(?)", self.user_id, Date.today).all.any?
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :correct_user, only: [:show, :destroy]
  skip_before_action :login_required, only: [:new, :create]
    
  def index
    @attendances = Attendance.all
    @attendances = Attendance.order("created_at DESC").page(params[:page])
  end

  def create
    @attendance = current_user.today_attendance
    started = start?(@attendance)
    ended = end?(@attendance)
    
    if (!started && !ended) || (started && ended)
      @attendance = current_user.attendances.build(start_at: Time.zone.now)
      flash[:success] = "#{Time.zone.now.strftime("%H:%M")}に出勤しました。"
    elsif started && !ended
      @attendance.end_at = Time.zone.now
      flash[:success] = "#{Time.zone.now.strftime("%H:%M")}に退勤しました。"
    end
      
    if @attendance.save && @attendance.start_at.present? && @attendance.end_at.nil?
      redirect_to controller: :quizzes, action: :show, id: (random)
    elsif @attendance.save && @attendance.end_at.present?
      redirect_to "/quizzes/#{random}"
    else
      flash.clear
      redirect_to request.referer
      flash[:danger] = "本日はすでに打刻済みです。"
    end
  end
    
  def edit
    @attendance = Attendance.find(params[:id])
    if @attendance.user == current_user || current_user.is_admin
      render "edit"
    else
      flash[:danger] = "権限がありません。"
      redirect_to request.referer
    end
  end
  
  def update
    @attendance = Attendance.find(params[:id])
    if @attendance.update(attendance_params)
      flash[:success] = "勤怠の修正を申請しました。"
      redirect_to attendances_path
    else
      flash[:danger] = "時間を確認してください。"
      redirect_to request.referer
    end
  end

  private
    def attendance_params
      params.require(:attendance).permit(:start_at, :end_at)
    end
  
    def correct_user
      @attendance = current_user.attendances.find_by(id: params[:id])
      redirect_to root_url if @attendance.nil?
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def random
    Quiz.pluck(:id).sample
  end
end

app/views/attendances/edit.html.erb
<div class="w-100 d-flex flex-column align-items-center">
  <h4><%= @attendance.user.name %>の勤怠編集</h4>
    <h4><%= form_for(@attendance) do |f| %>
      <%= f.label :start, '出勤時刻', class: 'm-3' %>
      <%= raw sprintf(
        f.datetime_select( 
          :start_at,
          {
            discard_year: true,
            discard_month: true,
            default: Time.zone.now,
            use_two_digit_numbers: true,
            datetime_separator: '%s',
            time_separator: '%s'
          },
        ),
        '時 ') + '分'
      %><br>
      
      <%= f.label :end, '退勤時刻', class: 'm-3' %>
      <%= raw sprintf(
        f.datetime_select( 
          :end_at,
          {
            discard_year: true,
            discard_month: true,
            default: Time.zone.now,
            use_two_digit_numbers: true,
            datetime_separator: '%s',
            time_separator: '%s'
          },
        ),
        '時 ') + '分'
      %><br>
      
      <% if current_user.is_admin? %>
        <%= f.submit "更新", class: "btn btn-outline-primary btn-lg m-3" %><br>
      <% else %>
        <%= f.submit "提出", class: "btn btn-outline-primary btn-lg m-3" %><br>
      <% end %>
      <%= link_to '勤怠状況一覧に戻る', attendances_path, class: "btn btn-outline-primary btn-lg m-3" %>
    <% end %>  
</div>

app/views/attendances/index.html.erb
<div class="w-100 d-flex flex-column align-items-center">
  <h4>勤怠状況一覧 (降順)</h4>
  <%= render 'shared/date' %>
</div> 

<div class="pagination justify-content-center">
  <h4><%= paginate @attendances %></h4>
</div>

<% if current_user.is_admin? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">名前</th>
        <th scope="col">出勤日</th>
        <th scope="col">出勤時間</th>
        <th scope="col">退勤時間</th>
        <th scope="col">勤務時間</th>
        <th scope="col">編集</th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |attendance| %>
        <tr>
          <td>
            <%= attendance.user.name %>
          </td>
          
          <td>
            <%= attendance.start_at.strftime("%Y年%m月%d日(%a)") %>
          </td>
          
          <td>
            <% if attendance.start_at.present? %>
              <%= attendance.start_at.strftime("%H:%M") %>
            <% else %>
              <div class="p-3 bg-danger text-light">まだ出勤打刻していないよ</div>
            <% end %>
          </td>
          
          <td>
            <% if attendance.end_at.present? %>
              <%= attendance.end_at.strftime("%H:%M") %>
            <% else %>
              <div class="p-3 bg-danger text-light">まだ退勤打刻していないよ</div>
            <% end %>
          </td>
          
          <td>
            <% if attendance.start_at.present? && attendance.end_at.present? %>
              <%= "#{(attendance.time_diff).round(1)}時間" %>
            <% else %>
              <div class="p-3 bg-danger text-light">--</div>
            <% end %>
          </td>
        
          <td>
            <%= link_to '編集', edit_attendance_path(attendance), class: 'btn btn-outline-primary' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">名前</th>
        <th scope="col">出勤日</th>
        <th scope="col">出勤時間</th>
        <th scope="col">退勤時間</th>
        <th scope="col">勤務時間</th>
        <th scope="col">編集</th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |attendance| %>
        <tr>
          <td>
            <% if attendance.user == current_user %>
              <%= attendance.user.name %>
            <% end %>
          </td>
      
          <td>
            <% if attendance.user == current_user %>
              <%= attendance.start_at.strftime("%Y年%m月%d日(%a)") %>
            <% end %>
          </td>
      
          <td>
            <% if attendance.user == current_user %>
              <% if attendance.start_at.present? %>
                <%= attendance.start_at.strftime("%H:%M") %>
              <% else %>
                <div class="p-3 bg-danger text-light">まだ出勤打刻していないよ</div>
              <% end %>
            <% end %>
          </td>
      
          <td>
            <% if attendance.user == current_user %>
              <% if attendance.end_at.present? %>
                <%= attendance.end_at.strftime("%H:%M") %>
              <% else %>
                <div class="p-3 bg-danger text-light">まだ退勤打刻していないよ</div>
              <% end %>
            <% end %>
          </td>
      
          <td>
            <% if attendance.user == current_user %>
              <% if attendance.start_at.present? && attendance.end_at.present? %>
                <%= "#{(attendance.time_diff).round(1)}時間" %>
              <% else %>
                <div class="p-3 bg-danger text-light">--</div>
              <% end %>
            <% end %>
          </td>
    
          <td>
            <% if attendance.user == current_user %>
              <%= link_to '編集', edit_attendance_path(attendance), class: 'btn btn-outline-primary' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>